services:
    main:
        image: 'notes-service:latest'
        build:
            context: .
        container_name: notes-back-app
        depends_on:
            - db
        environment:
            - POSTGRES_USER=some_user
            - POSTGRES_PASSWORD=some_password
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/notes
            - SPRING_DATASOURCE_USERNAME=some_user
            - SPRING_DATASOURCE_PASSWORD=some_password
            - JWT_SECRET=WlFWd1RaV0RFdgWlFWd1RaV0RFdgWlFWd1RaV0RFdgWlFWd1RaV0RFdgWlFWd1RaV0RFdgWlFWd1RaV0RFdgWlFWd1RaV0RFdg
            - JWT_EXPIRATION=86400000 # 24 hours

        ports:
            - "8080:8080"

    db:
        image: postgres
        container_name: notes-back-db
        environment:
            - POSTGRES_USER=some_user
            - POSTGRES_PASSWORD=some_password
            - POSTGRES_DB=notes
        ports:
            - "5432:5432"