services:
    main:
        image: 'notes-service:latest'
        build:
            context: .
        container_name: notes-back-app
        depends_on:
            - db
        env_file:
            -   .env

        ports:
            - "8080:8080"

    db:
        image: postgres
        container_name: notes-back-db
        env_file:
            -   .env
        ports:
            - "5432:5432"